name: Add reviewers to release PRs

on:
  pull_request_target:
    branches: ['master', 'next']
    types: ['labeled']

permissions: {}

jobs:
  add-reviewers-to-release-pr:
    uses: mui/mui-public/.github/workflows/reusable-add-reviewers-to-pr.yml@master
    with:
      team-slug: x
      label-name: release
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
