name: Update Charts Benchmark Baseline

on:
  push:
    branches:
      - 'master'
      - 'next'
    paths:
      - 'packages/x-charts*/**'
      - 'test/performance-charts/**'

jobs:
  performance-test:
    name: Update Charts Benchmark Baseline
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: read

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          run_install: false
      - name: Use Node.js 22.x
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 22
          cache: 'pnpm' # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
      - run: pnpm install --frozen-lockfile
      - run: pnpm exec playwright install
      - run: pnpm --filter "@mui/x-charts-premium..." build

      - name: Run performance tests
        run: pnpm --filter @mui-x-internal/performance-charts test:performance:ci
      - run: jq '.commit = "${{ github.sha }}"' test/performance-charts/results.json > test/performance-charts/baseline-results.json

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: charts-benchmarks-results-${{ github.ref_name }}.json
          path: ./test/performance-charts/baseline-results.json
          if-no-files-found: error
