name: Performance Test

on:
  pull_request:
    types:
      # Default
      - opened
      - synchronize
      - reopened
      # To run when the right labels are applied
      - labeled
    branches:
      - master
      - next

permissions: {}

jobs:
  performance-test:
    name: Benchmark Charts
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: read
    # L1: Run the benchmarks for pushes to the master or next branch and if the changes are in the charts package based on on.push.paths
    # L2: Run the benchmarks if we add the label 'scope: charts' to the pull request
    # L3: Run the benchmarks for pull requests with the label 'scope: charts'
    # Yaml syntax looks a little weird, but it is correct.
    if: >-
      ${{
          (github.event_name == 'push') ||
          (github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'scope: charts') ||
          (github.event_name == 'pull_request' && github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, 'scope: charts'))
      }}

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          run_install: false
      - name: Use Node.js 22.x
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 22.18.0
          cache: 'pnpm' # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
      - run: pnpm install --frozen-lockfile
      - run: pnpm exec playwright install
      # Ensure we are running on the prod version of our libs
      - run: pnpm --filter "@mui/x-charts-premium..." build

      - name: Download baseline results, if available
        run: |
          echo "Downloading baseline results from branch '${{ github.base_ref }}' for performance tests"
          gh run download --name "charts-benchmarks-results-${{ github.base_ref }}.json" || true
          [[ -e ./baseline-results.json ]] && echo "Found baseline, comparing results..." || echo "No baseline results found, skipping comparison"
          mv ./baseline-results.json ./test/performance-charts/baseline-results.json || true

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run performance tests
        run: pnpm --filter @mui-x-internal/performance-charts test:performance:ci

      - name: Compare performance results
        uses: actions/github-script@v7
        env:
          BASELINE_PATH: ./test/performance-charts/baseline-results.json
          COMPARE_PATH: ./test/performance-charts/results.json
          THRESHOLD: 0.1
        with:
          script: |
            const { default: ciBenchmark } = await import('${{ github.workspace }}/test/performance-charts/scripts/ci-benchmark.js');
            await ciBenchmark({github, context, core});
