name: Benchmarks

on:
  push:
    branches:
      - 'master'
      - 'next'
    paths:
      - 'packages/x-charts*/**'
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
    branches:
      - 'master'
      - 'next'

jobs:
  benchmarks:
    name: Benchmarks Charts
    runs-on: ubuntu-latest
    # L1: Run the benchmarks for pushes to the master or next branch and if the changes are in the charts package based on on.push.paths
    # L2: Run the benchmarks if we add the label 'component: charts' to the pull request
    # L3: Run the benchmarks for pull requests with the label 'component: charts'
    # Yaml syntax looks a little weird, but it is correct.
    if: >-
      ${{ 
          (github.event_name == 'push') || 
          (github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'component: charts') || 
          (github.event_name == 'pull_request' && github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, 'component: charts')) 
      }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          run_install: false
      - name: Use Node.js 20.x
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 20
          cache: 'pnpm' # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
      - run: pnpm install --frozen-lockfile
      # Ensure we are running on the prod version of our libs
      # Only charts and license are needed for the benchmarks
      - run: pnpm --filter @mui/x-license build
      - run: pnpm --filter @mui/x-charts build
      - run: pnpm --filter @mui/x-charts-pro build
      - name: Run benchmarks
        uses: CodSpeedHQ/action@86517f4abbb50982006ed33de6c22a586c7e11a1
        with:
          run: pnpm --filter @mui-x-internal/performance-charts test:performance
          token: ${{ secrets.CODSPEED_TOKEN }}
