name: Benchmarks

on:
  push:
    branches:
      - master
      - next
    paths:
      - 'packages/x-charts*/**'
  pull_request:
    types:
      # Default
      - opened
      - synchronize
      - reopened
      # To run when the right labels are applied
      - labeled
    branches:
      - master
      - next

permissions: {}

jobs:
  benchmarks:
    name: Benchmarks Charts
    runs-on: ubuntu-latest
    # L1: Run the benchmarks for pushes to the master or next branch and if the changes are in the charts package based on on.push.paths
    # L2: Run the benchmarks if we add the label 'scope: charts' to the pull request
    # L3: Run the benchmarks for pull requests with the label 'scope: charts'
    # Yaml syntax looks a little weird, but it is correct.
    if: >-
      ${{
          (github.event_name == 'push') ||
          (github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == 'scope: charts') ||
          (github.event_name == 'pull_request' && github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, 'scope: charts'))
      }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          run_install: false
      - name: Use Node.js 22.x
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 22.18.0
          cache: 'pnpm' # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
      - run: pnpm install --frozen-lockfile
      # Ensure we are running on the prod version of our libs
      - run: pnpm --filter "@mui/x-charts-premium..." build
      - name: Run benchmarks
        uses: CodSpeedHQ/action@653fdc30e6c40ffd9739e40c8a0576f4f4523ca1
        with:
          mode: walltime
          run: pnpm --filter @mui-x-internal/performance-charts test:performance
          token: ${{ secrets.CODSPEED_TOKEN }}
