# Inspired from https://github.com/redhat-developer/devspaces/tree/crw-2-rhel-8/.github/workflows
# To find more information about artifacts : https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts
name: PR check

on:
  pull_request:
    branches:
      - master

jobs:
  pull-request-info:
    runs-on: ubuntu-20.04
    steps:
      - name: Store PR info
        run: |
          echo "${{ github.event.number }}" > pr-number.txt
          echo "${{ github.event.pull_request.head.sha }}" > pr-sha.txt
      - uses: actions/upload-artifact@v3
        with:
          name: pull-request-sha
          path: pr-sha.txt
          retention-days: 1
